version: '3'
services:
  app:
    build: .
    env_file:
      - .env.development
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - db_network
    restart: always

networks: 
  db_network:
    driver: bridge